# -*- coding: utf-8 -*-
"""Python Programing Assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1buxUqprkd5B2nhQknTc4pn8fjfP8_IRg
"""

•	Write a Python program to convert kilometers to miles?
	•	Write a Python program to convert Celsius to Fahrenheit?
	•	Write a Python program to display calendar?
	•	Write a Python program to solve quadratic equation?
	•	Write a Python program to swap two variables without temp variable?

## •	Write a Python program to convert kilometers to miles?
a = 1.609

b = int(input("Enter the number of kilometers you want to change in miles"))
n = b/a
print(n)

## •	Write a Python program to convert Celsius to Fahrenheit?
a = int(input("Enter a number you want to conver in Fahrenheit:" ))	
b = (a * 9/5) + 32 
print(a,"Celsius is equal to", b, "Fahrenheit")

## 	Write a Python program to display calendar?
import calendar
yy = int(input("Enter year: "))
mm = int(input("Enter month: "))
print(calendar. month(yy,mm))

## 	Write a Python program to solve quadratic equation?
## ax2 + bx + c
#ax2 + bx + c
#where,
#a, b, and c are coefficient and real numbers and also a ≠ 0.
# If a is equal to 0 that equation is not valid quadratic equation.


# import complex math module
import cmath


try:
  

    a = float(input('Enter a: '))
    b = float(input('Enter b: '))
    c = float(input('Enter c: '))
except :
  print("Your code have value of a = 0")

# calculate the discriminant
d = (b**2) - (4*a*c)

# find two solutions
try:
   sol1 = (-b-cmath.sqrt(d))/(2*a)
   sol2 = (-b+cmath.sqrt(d))/(2*a)
except:
  print("complex division by zero error")

print('The solution are {0} and {1}'.format(sol1,sol2))

##  Write a Python program to swap two variables without temp variable?
# Python code to swap two numbers
# using Bitwise XOR method
 
 
x = 5  # x = 0101
y = 10 # y = 1010
 
print ("Before swapping: ")
print("Value of x : ", x, " and y : ", y)
 
# Swap code
x ^= y # x = 1111, y = 1010
y ^= x # y = 0101, x = 1111
x ^= y # x = 1010, y = 0101
 
print ("After swapping: ")
print("Value of x : ", x, " and y : ", y)

